(*<*)
theory Paper
imports
  "Earley.EarleyWorklist"
  Sugar
begin
declare [[show_question_marks=false]]
declare [[names_short=true]]
hide_const (open) \<alpha>
hide_const (open) \<beta>
(*>*)

text\<open>

\section{Introduction}

\section{Isabelle Notation} \label{sec:isabelle}


\subsection{Context-Free Grammars}

All our types are parameterized by type variables \<open>'n\<close> and \<open>'t\<close>, the types of \concept{nonterminals} and \concept{terminals}.
\concept{Symbols} are a tagged union type:
\begin{quote}
@{datatype sym}
\end{quote}
Variable convention:
% \<open>a, b, c :: 't\<close>, \<open>A, B, C :: 'n\<close> and  \<open>x, y, z :: ('n,'t) sym\<close>.
For compactness we sometimes drop the \<open>'n\<close> and \<open>'t\<close> parameters,
e.g.\ we write \<open>sym\<close> instead of \<open>('n,'t)sym\<close>.

A \concept{production}, informally written \<open>A \<rightarrow> \<alpha>\<close>, is a pair of \<open>A :: 'n\<close> and \<open>\<alpha>\<close> \<open>::\<close> \mbox{\<open>sym list\<close>}.
We use the following abbreviations:
\begin{quote}
\<open>syms = sym list\<close> \quad \<open>prod = 'n \<times> syms\<close> \quad \<open>Prods = prod set\<close>
\end{quote}
%Variable convention:
%\<open>w :: 't list\<close>; lists over terminal symbols are called \concept{terminal words};
%\<open>\<alpha>, \<beta>, \<gamma> :: syms\<close>; elements of type @{type syms} are called \concept{sentential forms}.

Our theory is primarily based on sets of productions rather than grammars:
the start symbol is irrelevant most of the time.
\emph{For succinctness, we use \concept{grammar} to refer to a set (or list) of productions.}
Moreover, we only restrict to finite sets of productions when necessary.

The identifier \<open>P\<close> is reserved for sets of productions.
Every \<open>P\<close> induces a single step derivation relation on \<open>syms\<close> in the standard manner:
\begin{quote}
@{thm derive.intros[of _ \<beta> _ \<alpha> \<gamma>]}
\end{quote}
Its transitive-reflexive closure is denoted by @{prop "P \<turnstile> \<alpha> \<Rightarrow>* \<beta>"}.

The language of some nonterminal \<open>A\<close> generated by \<open>P\<close> is easily defined:
\begin{quote}
@{thm Lang_def}
\end{quote}
\<close>

text (in Earley_Gw_eps)\<open>
\section{The Story so far}

\subsection{Inductive Definition of Earley's Item Sets} \label{sec:Earley}

An Earley recognizer decides if some word is in the language described by a grammar
by generating a set of so-called \emph{items}  (unfortunately called \emph{states} in \cite{NipowCBJ})
and checking if it contains a \emph{final} state.
In the sequel, we fix a grammar \<open>P\<close>, a start symbol \<open>S\<close> and an input \<open>w ::\<close> \mbox{@{type "syms"}}
consisting only of terminal symbols.

An item is a triple @{term "Item r d i"}
where \<open>r = (A, \<alpha>)\<close> is a production from \<open>P\<close>, \<open>d\<close> is a natural number such that@{prop "d \<le> length \<alpha>"},
indicating how far the algorithm has recognized \<open>\<alpha>\<close>,
and \<open>i\<close> is a natural number representing the start index of the subword of \<open>w\<close>
recognized by this item. The three projection functions are
@{const prod}, @{const dot} and @{const from}. We use the letters \<open>x\<close> and \<open>y\<close> for items.

A production \<open>A \<rightarrow> \<alpha>\<close> together
with a @{const dot} \<open>d\<close> is shown as \<open>A \<rightarrow> \<alpha>\<^sub>1\<Zspot>\<alpha>\<^sub>2\<close>, where \<open>\<alpha>\<^sub>1\<close> is the prefix of the first \<open>d\<close> symbols of \<open>\<alpha>\<close> and \<open>\<alpha>\<^sub>2\<close>
is the suffix. We will informally show item as pairs \<open>(A \<rightarrow> \<alpha>\<Zspot>\<beta>, i)\<close>.

Below we need the following auxiliary @{type item} functions that query or modify the dotted
production but not the @{const from} component of the state.
\begin{description}
\item[@{const_typ mv_dot}] moves the dot in a state one position to the right:
 @{const mv_dot} \<open>(A \<rightarrow> \<alpha>\<Zspot>s\<beta>, i) = (A \<rightarrow> \<alpha>s\<Zspot>\<beta>, i)\<close>
%\smallskip

\item[@{const_typ is_complete}] checks if the dotted production is of the form \mbox{\<open>A \<rightarrow> \<alpha>\<Zspot>\<close>}.
%\smallskip

\item[@{const_typ next_symbol}] is @{term None} if the state is complete, and \mbox{@{term "Some s"}}
if the dotted production is of the form \<open>A \<rightarrow> \<alpha>\<Zspot>s\<beta>\<close>.
\end{description}

Next we give an abstract inductive definition of @{const Earley}, we a single set
of pairs @{term "(x,j)"} of states and an index. However, it is more intuitive
to present it as an inductive definition of indexed state sets: we write
\mbox{@{prop "x \<in> \<S> j"}} instead of @{term "(x,j)"} \<open>\<in> Earley\<close>.
In the indexed presentation, we define state sets
\mbox{@{term "\<S> j"}}, @{prop \<open>j \<le> |w|\<close>}, that depend on each other. However, the dependence is in
one direction only: later sets depend on earlier ones, not the other way around.
Thus the @{term "\<S> j"} can be generated in ascending order. This is the subject of the next section
but plays no role now.

The intuitive meaning of @{prop "Item r d i \<in> \<S> j"} is that the subword
@{term "slice i j w"} (which stands for @{term "drop i (take j w)"}) has been recognized.
We call \<open>i\<close> the \emph{start index} and \<open>j\<close> the \emph{end index} (which is excluded).

The four defining rules are: the initial set of states, and one rule for each of the core operations that
expand the set of states: scanning, prediction, and completion.
\[ \inferrule {one \\ two \\ three \\ or \\ more \\ premisses}
{and \\ any \\ number \\ of \\ conclusions \\ as \\ well}\]
\begin{quote}
@{thm [mode=Rule] Earley.Init[simplified Earley_eq_\<S>]} {\sc Init}\smallskip\\
@{thm Init_def}
\end{quote}
\textsc{Init} adds all initial states \<open>(S \<rightarrow> \<Zspot>\<gamma>, 0)\<close> to @{term "\<S> 0"},
where @{term "S = start G"} and @{prop "(S,\<gamma>) \<in> set(prods G)"}.

\begin{quote}
@{thm [mode=Rule] Earley.Scan[simplified Earley_eq_\<S>]} {\sc Scan}
\end{quote}
\textsc{Scan} applies when there is a terminal symbol to the right of the dot
and it is the ``current'' symbol in the input \<open>w\<close>. In that case we move the dot
and add the new state into the next state set.

\begin{quote}
@{thm [mode=Rule] Earley.Predict[simplified Earley_eq_\<S>]} {\sc Predict}\smallskip\\
@{thm[margin=75,break] Predict_def}
\end{quote}
\textsc{Predict} is applicable to a state in @{term "\<S> k"} when there is a non-terminal symbol to the right of
the dot: \<open>A \<rightarrow> \<alpha>\<Zspot>B\<beta>, i\<close>. Then a new state \<open>(B \<rightarrow> \<Zspot>\<gamma>, k)\<close> can be added to  @{term "\<S> k"}
for each production @{term "(B, \<gamma>)"} of the grammar.

\begin{quote}
@{thm [mode=Rule,margin=60] Earley.Complete[simplified Earley_eq_\<S>]} {\sc Complete}
\end{quote}

\textsc{Complete} can be applied to all complete states \<open>(B \<rightarrow> \<gamma>\<Zspot>, j) \<in> \<S> k\<close>.
These states indicate successful recognition of @{term "slice j k w"} starting from \<open>B\<close>.
Hence we can move the dot over \<open>B\<close> in any production in @{term "\<S> j"}:
if \<open>(B \<rightarrow> \<alpha>\<Zspot>B\<beta>, i) \<in> \<S> j\<close> then we can add \<open>(B \<rightarrow> \<alpha>B\<Zspot>\<beta>, i)\<close> to @{term "\<S> k"}.

This concludes the inductive definition of the @{term "\<S> j"}.

\<close>
(*<*)
end
(*>*)